# ------------------------------------------
# Application
# ------------------------------------------
spring.application.name=mini-library
server.error.include-stacktrace=never
server.error.include-message=never

# ------------------------------------------
# Datasource (H2 in-memory)
# ------------------------------------------
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ------------------------------------------
# JPA / Hibernate
# ------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ------------------------------------------
# H2 Console
# ------------------------------------------
spring.h2.console.enabled=true
spring.h2.console.path=/lib-db-console

# ------------------------------------------
# Logging
# ------------------------------------------
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.com.ssd.minilibrary.security=INFO
logging.level.com.ssd.minilibrary.audit=INFO
